//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace libMiracle
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MiracleEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MiracleEntities object using the connection string found in the 'MiracleEntities' section of the application configuration file.
        /// </summary>
        public MiracleEntities() : base("name=MiracleEntities", "MiracleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MiracleEntities object.
        /// </summary>
        public MiracleEntities(string connectionString) : base(connectionString, "MiracleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MiracleEntities object.
        /// </summary>
        public MiracleEntities(EntityConnection connection) : base(connection, "MiracleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<altchar> altchars
        {
            get
            {
                if ((_altchars == null))
                {
                    _altchars = base.CreateObjectSet<altchar>("altchars");
                }
                return _altchars;
            }
        }
        private ObjectSet<altchar> _altchars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<character> characters
        {
            get
            {
                if ((_characters == null))
                {
                    _characters = base.CreateObjectSet<character>("characters");
                }
                return _characters;
            }
        }
        private ObjectSet<character> _characters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<dkp> dkps
        {
            get
            {
                if ((_dkps == null))
                {
                    _dkps = base.CreateObjectSet<dkp>("dkps");
                }
                return _dkps;
            }
        }
        private ObjectSet<dkp> _dkps;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the altchars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaltchars(altchar altchar)
        {
            base.AddObject("altchars", altchar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the characters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocharacters(character character)
        {
            base.AddObject("characters", character);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the dkps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodkps(dkp dkp)
        {
            base.AddObject("dkps", dkp);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="miraclehunModel", Name="altchar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class altchar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new altchar object.
        /// </summary>
        /// <param name="alt_id">Initial value of the alt_id property.</param>
        /// <param name="main_id">Initial value of the main_id property.</param>
        public static altchar Createaltchar(global::System.Int32 alt_id, global::System.Int32 main_id)
        {
            altchar altchar = new altchar();
            altchar.alt_id = alt_id;
            altchar.main_id = main_id;
            return altchar;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 alt_id
        {
            get
            {
                return _alt_id;
            }
            set
            {
                if (_alt_id != value)
                {
                    Onalt_idChanging(value);
                    ReportPropertyChanging("alt_id");
                    _alt_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("alt_id");
                    Onalt_idChanged();
                }
            }
        }
        private global::System.Int32 _alt_id;
        partial void Onalt_idChanging(global::System.Int32 value);
        partial void Onalt_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 main_id
        {
            get
            {
                return _main_id;
            }
            set
            {
                Onmain_idChanging(value);
                ReportPropertyChanging("main_id");
                _main_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("main_id");
                Onmain_idChanged();
            }
        }
        private global::System.Int32 _main_id;
        partial void Onmain_idChanging(global::System.Int32 value);
        partial void Onmain_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="miraclehunModel", Name="character")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class character : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new character object.
        /// </summary>
        /// <param name="keycode">Initial value of the keycode property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="class">Initial value of the class property.</param>
        /// <param name="role_main">Initial value of the role_main property.</param>
        /// <param name="role_alt">Initial value of the role_alt property.</param>
        /// <param name="profession_main">Initial value of the profession_main property.</param>
        /// <param name="profession_alt">Initial value of the profession_alt property.</param>
        /// <param name="rank">Initial value of the rank property.</param>
        /// <param name="join_date">Initial value of the join_date property.</param>
        public static character Createcharacter(global::System.Int32 keycode, global::System.String name, global::System.SByte @class, global::System.Boolean role_main, global::System.Boolean role_alt, global::System.SByte profession_main, global::System.SByte profession_alt, global::System.String rank, global::System.DateTime join_date)
        {
            character character = new character();
            character.keycode = keycode;
            character.name = name;
            character.@class = @class;
            character.role_main = role_main;
            character.role_alt = role_alt;
            character.profession_main = profession_main;
            character.profession_alt = profession_alt;
            character.rank = rank;
            character.join_date = join_date;
            return character;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 keycode
        {
            get
            {
                return _keycode;
            }
            set
            {
                if (_keycode != value)
                {
                    OnkeycodeChanging(value);
                    ReportPropertyChanging("keycode");
                    _keycode = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("keycode");
                    OnkeycodeChanged();
                }
            }
        }
        private global::System.Int32 _keycode;
        partial void OnkeycodeChanging(global::System.Int32 value);
        partial void OnkeycodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte @class
        {
            get
            {
                return _class;
            }
            set
            {
                OnclassChanging(value);
                ReportPropertyChanging("class");
                _class = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("class");
                OnclassChanged();
            }
        }
        private global::System.SByte _class;
        partial void OnclassChanging(global::System.SByte value);
        partial void OnclassChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_main
        {
            get
            {
                return _is_main;
            }
            set
            {
                Onis_mainChanging(value);
                ReportPropertyChanging("is_main");
                _is_main = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("is_main");
                Onis_mainChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_main;
        partial void Onis_mainChanging(Nullable<global::System.Boolean> value);
        partial void Onis_mainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean role_main
        {
            get
            {
                return _role_main;
            }
            set
            {
                Onrole_mainChanging(value);
                ReportPropertyChanging("role_main");
                _role_main = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("role_main");
                Onrole_mainChanged();
            }
        }
        private global::System.Boolean _role_main;
        partial void Onrole_mainChanging(global::System.Boolean value);
        partial void Onrole_mainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean role_alt
        {
            get
            {
                return _role_alt;
            }
            set
            {
                Onrole_altChanging(value);
                ReportPropertyChanging("role_alt");
                _role_alt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("role_alt");
                Onrole_altChanged();
            }
        }
        private global::System.Boolean _role_alt;
        partial void Onrole_altChanging(global::System.Boolean value);
        partial void Onrole_altChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte profession_main
        {
            get
            {
                return _profession_main;
            }
            set
            {
                Onprofession_mainChanging(value);
                ReportPropertyChanging("profession_main");
                _profession_main = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("profession_main");
                Onprofession_mainChanged();
            }
        }
        private global::System.SByte _profession_main;
        partial void Onprofession_mainChanging(global::System.SByte value);
        partial void Onprofession_mainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.SByte profession_alt
        {
            get
            {
                return _profession_alt;
            }
            set
            {
                Onprofession_altChanging(value);
                ReportPropertyChanging("profession_alt");
                _profession_alt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("profession_alt");
                Onprofession_altChanged();
            }
        }
        private global::System.SByte _profession_alt;
        partial void Onprofession_altChanging(global::System.SByte value);
        partial void Onprofession_altChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rank
        {
            get
            {
                return _rank;
            }
            set
            {
                OnrankChanging(value);
                ReportPropertyChanging("rank");
                _rank = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rank");
                OnrankChanged();
            }
        }
        private global::System.String _rank;
        partial void OnrankChanging(global::System.String value);
        partial void OnrankChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime join_date
        {
            get
            {
                return _join_date;
            }
            set
            {
                Onjoin_dateChanging(value);
                ReportPropertyChanging("join_date");
                _join_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("join_date");
                Onjoin_dateChanged();
            }
        }
        private global::System.DateTime _join_date;
        partial void Onjoin_dateChanging(global::System.DateTime value);
        partial void Onjoin_dateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="miraclehunModel", Name="dkp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class dkp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new dkp object.
        /// </summary>
        /// <param name="dkp_id">Initial value of the dkp_id property.</param>
        /// <param name="keycode">Initial value of the keycode property.</param>
        /// <param name="points">Initial value of the points property.</param>
        public static dkp Createdkp(global::System.Int32 dkp_id, global::System.Int32 keycode, global::System.Int32 points)
        {
            dkp dkp = new dkp();
            dkp.dkp_id = dkp_id;
            dkp.keycode = keycode;
            dkp.points = points;
            return dkp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dkp_id
        {
            get
            {
                return _dkp_id;
            }
            set
            {
                if (_dkp_id != value)
                {
                    Ondkp_idChanging(value);
                    ReportPropertyChanging("dkp_id");
                    _dkp_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dkp_id");
                    Ondkp_idChanged();
                }
            }
        }
        private global::System.Int32 _dkp_id;
        partial void Ondkp_idChanging(global::System.Int32 value);
        partial void Ondkp_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 keycode
        {
            get
            {
                return _keycode;
            }
            set
            {
                OnkeycodeChanging(value);
                ReportPropertyChanging("keycode");
                _keycode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("keycode");
                OnkeycodeChanged();
            }
        }
        private global::System.Int32 _keycode;
        partial void OnkeycodeChanging(global::System.Int32 value);
        partial void OnkeycodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 points
        {
            get
            {
                return _points;
            }
            set
            {
                OnpointsChanging(value);
                ReportPropertyChanging("points");
                _points = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("points");
                OnpointsChanged();
            }
        }
        private global::System.Int32 _points;
        partial void OnpointsChanging(global::System.Int32 value);
        partial void OnpointsChanged();

        #endregion
    
    }

    #endregion
    
}
